### ISSUE TITLE
Voting system bug

### ISSUE THREAD

**Issue by wvicioso** [wvicioso/hackoverflow#55]
Vote count changes by 2 instead of 1

**Comment by LevytsRoman** [comment]
On questions user already voted it will change by 2 if you vote the other way, so if you've already upvoted something, then decided to downvote it instead it should change by 2 because you take away 1 upvote and you give 1 downvote. 

I just played with voting some more, and it does seem to have bugs where more then one downvote seems to be allowed, not sure why it's happening. Added some comments to vote logic in the controller.

**Comment by LevytsRoman** [comment]
After rebuilding seed file to make sure each user has only one vote on questions and answers the bug seems to be fixed.
